### PR TITLE
Configured Prettier in ESLint

### PR DESCRIPTION
**Pull request by gorkalaucirica**
Pending:

- Wait for #13 
- Run eslint to autofix errors

### CODE REVIEW

**Comment by benatespina** [comment]
Be careful with that. You can generate side-effects applying rules that they can override among ESLint and Prettier.
If it works fine, I totally agree with it.

**Comment by gorkalaucirica** [comment]
Will check before merging

**Comment by gorkalaucirica** [comment]
@benatespina This one is OK to review.

I reverted prettier rules to be aligned with standards.

**Comment by benatespina** [comment]
@gorkalaucirica mmmm I'm not feel very comfortable with some rules that you've been enabled.

I prefer to maintain `single-quote`, `no-bracket-spacing` and `trailing-commas` enabled like we have in master. You can custom prettier rules easily adding the following file, `.prettierrc.js`:
```js
module.exports = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: false,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  rangeStart: 0,
  rangeEnd: Infinity,
};
```

**Comment by gorkalaucirica** [comment]
CS discussions... personal opinions. 

I would stick to standards, but I don't want to spend time on this one. Standards can be changed at any time and fixed just running a command.

Push your proposal, I will be happy to merge whatever you consider.

**Comment by benatespina** [comment]
> CS discussions... personal opinions.
> 
> I would stick to standards, but I don't want to spend time on this one. Standards can be changed at any time and fixed just running a command.
> 
> Push your proposal, I will be happy to merge whatever you consider.

XD Thanks for your open-mind in that controversial topic, however I think that you can read the code more easy. :)

* Single quotes, because in dynamic languages (not only en JS, also for example en PHP) they're faster than double quote. (Yeah, I know, we are "Babelifying" our code, but.... :) )
* Trailing commas, because they improve code reviews when we are adding a new parameter and so on, diff is only generated in the exact line.
* No bracket spacing, it does not have any interesting reason, but this is because we have configured by default in PHPStorm, WebStorm, IntelliJ...

BTW, now it's good to merge for me. Go ahead if you think the same!

**Pull request merged**
